jobs:
- name: hello-world-pipeline
  plan:
  - task: echo-hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello World!"]
